spring:
  application:
    name: IDENTITY-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 9898
  
#  web:
#  cors:
#    allowed-origins: "http://localhost:4200"
#    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
#    max-age: 3600
#    allowed-headers: "Requestor-Type"
#    exposed-headers: "X-Get-Header"